### ISSUE TITLE
大佬镜像可以更新个log正常的吗?

### ISSUE THREAD

**Issue by 2375399351** [madwind/docker-flexget#1]
我之前用3.1.110正常，这个3.2的log好像都不显示

**Comment by madwind** [comment]
哪里不正常

**Comment by 2375399351** [comment]
> 哪里不正常

log不显示
[https://uploadbeta.com/share-image/gT2](url)

**Comment by madwind** [comment]
> > 哪里不正常
> 
> log不显示 [https://uploadbeta.com/share-image/gT2](url)

这应该是你log太多了 读得慢

**Comment by 2375399351** [comment]
> > > 哪里不正常
> > 
> > 
> > log不显示 [https://uploadbeta.com/share-image/gT2](url)
> 
> 这应该是你log太多了 读得慢

没有我是新建的容器，就是用的你的那个容器，版本是3.2.1

**Comment by madwind** [comment]
> > > > 哪里不正常
> > > 
> > > 
> > > log不显示 [https://uploadbeta.com/share-image/gT2](url)
> > 
> > 
> > 这应该是你log太多了 读得慢
> 
> 没有我是新建的容器，就是用的你的那个容器，版本是3.2.1

但是我看这几个版本好像也没有更新和log有关的，我跑一遍action看看 不一定行 大概要几个小时

**Comment by 2375399351** [comment]
> 

好的，谢谢，你可以试试看3.2.1这个版本的flexget的log有没有显示，好像flexget的web经常有log不显示的bug

**Comment by madwind** [comment]
所以我都很少看webui的log 直接看docker的log更方便 也不会卡

**Comment by 2375399351** [comment]
sort_by: qbittorrent_last_activity
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_keeper_template

大佬，这个自带删种是不是可以从  qbittorrent_add_template:里面设置的分类，再通过qbittorrent_delete_keeper_template设置的删种并删除数据，来实现自带删除指定分类的种子及数据？分类是在  qbittorrent_add_template:里面设置的

**Comment by madwind** [comment]
可以，但是他们之间没有关联，删除哪个分类是 if 里判断的 category

**Comment by 2375399351** [comment]
> category

ok，谢谢

**Comment by madwind** [comment]
更新测试过 还是打不开 只能删数据库了
