### ISSUE TITLE
新编译出来的镜像flexget版本在3.2.3或者3.2.4

### ISSUE THREAD

**Issue by barton0426** [madwind/docker-flexget#2]
log不显示 一直显示streaming
另外history也看不到
不知道什么原因

**Comment by madwind** [comment]
我也看到是webui的 js报错 我试试看换个

**Comment by madwind** [comment]
5小时之后更新看看，如果不行 我也没办法了，直接看docker的log吧

**Comment by barton0426** [comment]
似乎是webui自身的问题  https://github.com/Flexget/webui/issues/155
只能坐等官方修复了
